universe = vanilla
Executable = runOnCondor.sh
should_transfer_files = YES
WhenToTransferOutput  = ON_EXIT
Transfer_Input_Files = simBuffer_withTriggerRules_2in8.py, runOnCondor.sh
notification = never
Output = logs/condorRun_$(cluster)_$(process).stdout
Error = logs/condorRun_$(cluster)_$(process).stderr
Log = logs/condorRun_$(cluster)_$(process).condor
request_memory = 4000
request_disk = 10000000
x509userproxy = $ENV(X509_USER_PROXY)
Arguments = "$(process) 640 8"
Queue 100
